// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-retailers.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/data/mockData.ts
var dealers = [
  { id: "1", name: "Jai Maharashtra Hardware & Electricals", location: "Hinjewadi, Pimpri-Chinchwad, MH", type: "loyal", engagementScore: 85, openness: "high", lastVisit: "Last visited: 2 days ago", lastOutcome: "Positive \u2013 productive conversation on product range", area: "Hinjewadi", dealerCode: "JMH-001", revenueCategory: "A", lat: 18.52, lng: 73.84 },
  { id: "2", name: "Sharma Building Materials", location: "Pune West, MH", type: "new", engagementScore: 40, openness: "medium", lastVisit: "Last visited: 1 week ago", lastOutcome: "Introduction completed", area: "Pune West", dealerCode: "SBM-002", revenueCategory: "B", lat: 18.53, lng: 73.92 },
  { id: "3", name: "Krishna Traders", location: "Pune South, MH", type: "declining", engagementScore: 30, openness: "low", lastVisit: "Last visited: 3 weeks ago", lastOutcome: "Unresponsive \u2013 competitor focus", area: "Pune South", dealerCode: "KT-003", revenueCategory: "C", lat: 18.48, lng: 73.87 },
  { id: "4", name: "Gupta Cement House", location: "Pune North, MH", type: "inactive", engagementScore: 20, openness: "low", lastVisit: "Last visited: 1 month ago", lastOutcome: "Shop closed during visit", area: "Pune North", dealerCode: "GCH-004", revenueCategory: "C", lat: 18.57, lng: 73.85 },
  { id: "5", name: "Rajesh Construction Supply", location: "Pune NE, MH", type: "loyal", engagementScore: 92, openness: "high", lastVisit: "Last visited: Yesterday", lastOutcome: "Great discussion on expanding product range", area: "Pune NE", dealerCode: "RCS-005", revenueCategory: "A", lat: 18.56, lng: 73.93 },
  { id: "6", name: "Patel & Sons Hardware", location: "Pune NE, MH", type: "new", engagementScore: 55, openness: "high", lastVisit: "Last visited: 3 days ago", lastOutcome: "First meeting \u2013 willing to explore JK products", area: "Pune NE", dealerCode: "PSH-006", revenueCategory: "B", lat: 18.49, lng: 73.92 },
  { id: "7", name: "Singh Building Centre", location: "Pune SW, MH", type: "declining", engagementScore: 35, openness: "medium", lastVisit: "Last weeks ago", lastOutcome: "Needs more engagement attention", area: "Pune SW", dealerCode: "SBC-007", revenueCategory: "B", lat: 18.56, lng: 73.81 },
  { id: "8", name: "Mahalaxmi Traders", location: "Pune SW, MH", type: "loyal", engagementScore: 78, openness: "high", lastVisit: "Last visited: 4 days ago", lastOutcome: "Strong relationship \u2013 regular engagement", area: "Pune SW", dealerCode: "MT-008", revenueCategory: "A", lat: 18.49, lng: 73.82 },
  { id: "9", name: "Deshpande Hardware Stores", location: "Pune North, MH", type: "inactive", engagementScore: 38, openness: "medium", lastVisit: "Last visited: 5 weeks ago", lastOutcome: "Open to re-engagement \u2013 cited service gaps", area: "Pune North", dealerCode: "DHS-009", revenueCategory: "B", lat: 18.58, lng: 73.86 }
];
var engagementThemes = [
  {
    id: "et1",
    title: "Alignment to JK's Vision of Multi-Products",
    subtitle: "Help retailers see the opportunity in a multi-product portfolio",
    icon: "Layers",
    color: "primary",
    discussionPoints: [
      {
        id: "dp1",
        title: "Higher Profit Pool",
        description: "Multi-product play increases margins vs single-product reliance",
        detail: "Retailers stocking putty, white cement, and paints see 25-35% higher margins compared to cement-only retailers. The multi-product portfolio reduces dependency on seasonal cement demand and creates year-round revenue streams."
      },
      {
        id: "dp2",
        title: "Full Customer Solution",
        description: "Capture the entire demand cycle from base to finish",
        detail: "When a contractor visits your shop for cement, they also need putty, white cement, and paints. By offering the complete JK range, you become a one-stop solution - reducing customer leakage to competitors."
      },
      {
        id: "dp3",
        title: "Low-Risk Expansion",
        description: "Begin with limited SKUs and scale gradually with company support",
        detail: "Start with just 5-8 SKUs across categories. JK provides free display materials, and a dedicated support team. Scale up only when you see traction - zero pressure, full flexibility."
      }
    ],
    whatIfs: [
      {
        id: "wi1",
        label: "Demand-related in my area",
        peerLearning: "Retailers in similar markets started with a small trial and saw demand grow as contractors discovered the quality. Initial demand is created through awareness, not existing demand.",
        dealerStory: ""
      },
      {
        id: "wi2",
        label: "Working capital will get blocked",
        peerLearning: "Many retailers start with a minimum order and see turnover within 2-3 weeks. Start small and scale based on traction.",
        dealerStory: ""
      },
      {
        id: "wi3",
        label: "No space in the shop",
        peerLearning: "JK's compact multi-product display stand takes just 4 sq ft and is designed for small shops. It's provided free and positioned for visibility.",
        dealerStory: ""
      },
      {
        id: "wi4",
        label: "What if it doesn't work?",
        peerLearning: "Start with the top 3 proven sellers in your market segment and set a 30-day review checkpoint. Most retailers see traction within the first month.",
        dealerStory: ""
      }
    ]
  },
  {
    id: "et2",
    title: "Getting Initial Success as a New Retailer",
    subtitle: "Build confidence and momentum in the first 90 days",
    icon: "Rocket",
    color: "info",
    discussionPoints: [
      {
        id: "dp4",
        title: "Quick Wins Strategy",
        description: "Focus on high-demand, fast-moving SKUs first",
        detail: "Start with JK's top 5 best-selling SKUs in your area. These products have proven demand and quick turnaround - giving you confidence and cash flow within the first 2-3 weeks."
      },
      {
        id: "dp5",
        title: "Contractor Network Building",
        description: "Connect with local contractors through JK's network",
        detail: "JK facilitates introductions to active contractors in your area. Building relationships with contractors creates a sustainable pull for JK products through your shop."
      },
      {
        id: "dp6",
        title: "Marketing & Visibility Support",
        description: "Free in-shop branding and local marketing campaigns",
        detail: "JK provides shop board branding, product displays, and local advertising support at zero cost. This establishes you as an authorized JK retailer and drives footfall from day one."
      }
    ],
    whatIfs: [
      {
        id: "wi5",
        label: "I already have established brands",
        peerLearning: "JK doesn't replace your existing brands - it adds a premium tier. Retailers who added JK alongside existing brands saw increased footfall without cannibalizing existing sales.",
        dealerStory: ""
      },
      {
        id: "wi6",
        label: "I'm not sure about the quality",
        peerLearning: "JK Cement has 40+ years of trust. Free product samples are available for you and your contractors to test. Most retailers who tested the products were convinced by the quality.",
        dealerStory: ""
      }
    ]
  },
  {
    id: "et3",
    title: "Building a Pool of Contractors / Painters",
    subtitle: "Create a sustainable network of influencers who drive demand",
    icon: "Users",
    color: "success",
    discussionPoints: [
      {
        id: "dp7",
        title: "Contractor Engagement",
        description: "Build lasting relationships with contractors who use JK products",
        detail: "Engage contractors through product training, knowledge sharing, and consistent quality. This positions you as a trusted partner and knowledge hub in your area."
      },
      {
        id: "dp8",
        title: "Technical Training Sessions",
        description: "Free training builds contractor confidence and trust",
        detail: "JK conducts free application training for contractors at your shop. This positions you as a knowledge hub, builds trust, and ensures contractors apply products correctly - reducing complaints."
      },
      {
        id: "dp9",
        title: "Painter Meet Programs",
        description: "Organized events to engage painters in your area",
        detail: "JK sponsors painter meets with product demos, lucky draws, and networking. These events build your reputation as a community hub and create word-of-mouth demand for JK products."
      }
    ],
    whatIfs: [
      {
        id: "wi7",
        label: "Contractors prefer other brands",
        peerLearning: "Contractors follow quality and support. Once contractors attend a JK training session and experience the product, most build a preference over time through consistent results.",
        dealerStory: ""
      },
      {
        id: "wi8",
        label: "I don't know enough contractors",
        peerLearning: "JK's field team helps identify and connect you with active contractors in your area. On average, each new retailer is introduced to 8-12 contractors within the first month.",
        dealerStory: ""
      }
    ]
  }
];
var discussionPoints = [
  {
    id: "1",
    title: "JK Product Range \u2013 Multi-Product Awareness",
    bullets: [
      "JK Cement offers a comprehensive product portfolio across categories",
      "Product range covers cement, white cement, putty, and paints",
      "Opportunity to become a one-stop solution for contractors",
      "Marketing support with in-shop branding and visibility materials"
    ],
    objections: [
      { id: "o1", label: "Already selling other brands", response: "JK complements existing brands as a premium option. More product choices mean more footfall and a stronger position as a go-to retailer." },
      { id: "o2", label: "Demand-related in my area", response: "Demand often starts with visibility. Retailers in similar markets found that once JK products were displayed, contractor enquiries followed naturally." },
      { id: "o3", label: "Not sure about stocking new products", response: "Start with a small trial of fast-moving SKUs. Assess traction over 30 days before deciding on next steps." }
    ]
  },
  {
    id: "2",
    title: "JK White Cement \u2013 Seasonal Opportunity",
    bullets: [
      "Festival season typically sees higher demand for white cement",
      "New consumer-friendly packaging in 1kg and 5kg packs",
      "JK provides display materials for in-shop visibility",
      "Contractor demand remains strong year-round"
    ],
    objections: [
      { id: "o4", label: "No space in shop", response: "JK's compact display stand takes just 2 sq ft and is designed for small shops. It's positioned to draw attention without taking floor space." },
      { id: "o5", label: "What if it doesn't sell", response: "White cement has consistent year-round demand. Start with a small quantity and scale based on actual sell-through." }
    ]
  },
  {
    id: "3",
    title: "Relationship & Trust Building",
    bullets: [
      "Check on any pending issues or service gaps",
      "Discuss retailer's business growth and how JK can support",
      "Share success stories from similar retailers in the region",
      "Understand competitive landscape in the retailer's area"
    ],
    objections: [
      { id: "o6", label: "JK delivery is often delayed", response: "We've expanded distribution points in your zone. Share any specific incidents and I'll escalate immediately for resolution." }
    ]
  },
  {
    id: "4",
    title: "Retailer Support & Knowledge Building",
    bullets: [
      "Technical training for retailer staff on product applications",
      "Annual retailer meet and recognition events",
      "Priority access to new product information",
      "Ongoing ME support for business growth conversations"
    ],
    objections: [
      { id: "o7", label: "I don't see enough support from JK", response: "JK is committed to being a long-term partner. Let's identify specific areas where you need more support and we'll work on it together." }
    ]
  },
  {
    id: "5",
    title: "Market Intelligence & Feedback",
    bullets: [
      "Understand customer preferences and trending products",
      "Identify upcoming construction projects in the area",
      "Note any new competitors entering the market",
      "Gather insights on what contractors are looking for"
    ],
    objections: []
  }
];
var objectionBreakdown = [
  { name: "Demand-related", value: 28 },
  { name: "Working capital", value: 22 },
  { name: "SKU space", value: 18 },
  { name: "Competition from other brands", value: 17 },
  { name: "Poor Product Quality", value: 15 }
];

// src/lib/mcp/tools/list-retailers.ts
var list_retailers_default = defineTool({
  name: "list_retailers",
  title: "List retailers",
  description: "List retailers (dealers) in the Pune trading area with their segment, engagement score, openness and last visit outcome. Optionally filter by segment or area.",
  inputSchema: {
    segment: z.enum(["new", "loyal", "inactive", "declining"]).optional().describe("Filter by retailer segment."),
    area: z.string().optional().describe("Filter by market area, e.g. 'Hinjewadi'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ segment, area }) => {
    const rows = dealers.filter(
      (d) => (!segment || d.type === segment) && (!area || d.area.toLowerCase().includes(area.toLowerCase()))
    );
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, retailers: rows }
    };
  }
});

// src/lib/mcp/tools/get-retailer.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_retailer_default = defineTool2({
  name: "get_retailer",
  title: "Get retailer snapshot",
  description: "Get the full snapshot for one retailer by id, dealer code, or (partial) name.",
  inputSchema: {
    query: z2.string().min(1).describe("Retailer id, dealer code, or part of the name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query.trim().toLowerCase();
    const dealer = dealers.find((d) => d.id === q || d.dealerCode.toLowerCase() === q) ?? dealers.find((d) => d.name.toLowerCase().includes(q));
    if (!dealer) throw new ToolError(`No retailer matched "${query}".`);
    return {
      content: [{ type: "text", text: JSON.stringify(dealer, null, 2) }],
      structuredContent: { retailer: dealer }
    };
  }
});

// src/lib/mcp/tools/list-market-insights.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";

// src/data/leadershipData.ts
var NATIONAL_TOTAL_RETAILERS = 55e3;
var NATIONAL_RETAILERS_ENGAGED = 41250;
var NATIONAL_TOTAL_MES = 400;
var NATIONAL_ACTIVE_MES = 332;
var NATIONAL_TOTAL_ASMS = 46;
var ENGAGEMENT_BENCHMARK_PER_RETAILER = 4;
var NATIONAL_AVG_ENGAGEMENT_PER_RETAILER = 4.6;
var states = [
  {
    state: "Maharashtra",
    stateHead: "R. Iyer",
    totalMes: 48,
    activeMes: 42,
    totalRetailers: 7200,
    retailersEngaged: 5760,
    unitsCovered: 5,
    status: "on-track",
    segments: { new: 1080, loyal: 2880, inactive: 1800, declining: 1440 },
    areas: [
      { area: "Pune", asm: "Rajesh Kumar", totalMes: 7, activeMes: 6, totalRetailers: 1300, retailersEngaged: 1100, unitsCovered: 5, status: "on-track" },
      { area: "Mumbai", asm: "S. Bhide", totalMes: 9, activeMes: 8, totalRetailers: 1700, retailersEngaged: 1410, unitsCovered: 4, status: "on-track" },
      { area: "Nagpur", asm: "P. Joshi", totalMes: 6, activeMes: 5, totalRetailers: 1050, retailersEngaged: 780, unitsCovered: 4, status: "lagging" },
      { area: "Nashik", asm: "K. Patil", totalMes: 5, activeMes: 4, totalRetailers: 900, retailersEngaged: 660, unitsCovered: 3, status: "lagging" },
      { area: "Aurangabad", asm: "M. Kale", totalMes: 5, activeMes: 5, totalRetailers: 850, retailersEngaged: 720, unitsCovered: 4, status: "on-track" }
    ]
  },
  {
    state: "Gujarat",
    stateHead: "H. Mehta",
    totalMes: 42,
    activeMes: 36,
    totalRetailers: 6400,
    retailersEngaged: 4900,
    unitsCovered: 4,
    status: "on-track",
    segments: { new: 1024, loyal: 2304, inactive: 1792, declining: 1280 },
    areas: [
      { area: "Ahmedabad", asm: "V. Shah", totalMes: 8, activeMes: 7, totalRetailers: 1400, retailersEngaged: 1180, unitsCovered: 5, status: "on-track" },
      { area: "Surat", asm: "N. Patel", totalMes: 7, activeMes: 6, totalRetailers: 1200, retailersEngaged: 950, unitsCovered: 4, status: "on-track" },
      { area: "Vadodara", asm: "B. Desai", totalMes: 6, activeMes: 5, totalRetailers: 1050, retailersEngaged: 780, unitsCovered: 4, status: "lagging" },
      { area: "Rajkot", asm: "C. Joshi", totalMes: 5, activeMes: 4, totalRetailers: 900, retailersEngaged: 660, unitsCovered: 3, status: "lagging" }
    ]
  },
  {
    state: "Rajasthan",
    stateHead: "A. Singh",
    totalMes: 38,
    activeMes: 33,
    totalRetailers: 5600,
    retailersEngaged: 4200,
    unitsCovered: 4,
    status: "on-track",
    segments: { new: 896, loyal: 2016, inactive: 1568, declining: 1120 },
    areas: [
      { area: "Jaipur", asm: "D. Sharma", totalMes: 9, activeMes: 8, totalRetailers: 1500, retailersEngaged: 1230, unitsCovered: 5, status: "on-track" },
      { area: "Jodhpur", asm: "L. Rathod", totalMes: 6, activeMes: 5, totalRetailers: 1100, retailersEngaged: 820, unitsCovered: 4, status: "on-track" },
      { area: "Udaipur", asm: "T. Mehta", totalMes: 5, activeMes: 4, totalRetailers: 900, retailersEngaged: 620, unitsCovered: 3, status: "lagging" }
    ]
  },
  {
    state: "Karnataka",
    stateHead: "G. Rao",
    totalMes: 36,
    activeMes: 30,
    totalRetailers: 5200,
    retailersEngaged: 3850,
    unitsCovered: 4,
    status: "on-track",
    segments: { new: 832, loyal: 1872, inactive: 1456, declining: 1040 },
    areas: [
      { area: "Bengaluru", asm: "S. Nayak", totalMes: 12, activeMes: 10, totalRetailers: 1900, retailersEngaged: 1480, unitsCovered: 5, status: "on-track" },
      { area: "Mysuru", asm: "R. Gowda", totalMes: 6, activeMes: 5, totalRetailers: 1e3, retailersEngaged: 720, unitsCovered: 4, status: "on-track" },
      { area: "Hubballi", asm: "P. Hegde", totalMes: 5, activeMes: 4, totalRetailers: 850, retailersEngaged: 580, unitsCovered: 3, status: "lagging" }
    ]
  },
  {
    state: "Tamil Nadu",
    stateHead: "K. Subramanian",
    totalMes: 34,
    activeMes: 28,
    totalRetailers: 5e3,
    retailersEngaged: 3650,
    unitsCovered: 3,
    status: "lagging",
    segments: { new: 800, loyal: 1750, inactive: 1500, declining: 950 },
    areas: [
      { area: "Chennai", asm: "M. Arumugam", totalMes: 11, activeMes: 9, totalRetailers: 1800, retailersEngaged: 1380, unitsCovered: 4, status: "on-track" },
      { area: "Coimbatore", asm: "V. Ramesh", totalMes: 7, activeMes: 6, totalRetailers: 1100, retailersEngaged: 820, unitsCovered: 3, status: "lagging" },
      { area: "Madurai", asm: "S. Pillai", totalMes: 5, activeMes: 4, totalRetailers: 900, retailersEngaged: 560, unitsCovered: 2, status: "lagging" }
    ]
  },
  {
    state: "Uttar Pradesh",
    stateHead: "R. Pandey",
    totalMes: 40,
    activeMes: 31,
    totalRetailers: 5800,
    retailersEngaged: 4100,
    unitsCovered: 3,
    status: "lagging",
    segments: { new: 928, loyal: 2030, inactive: 1740, declining: 1102 },
    areas: [
      { area: "Lucknow", asm: "A. Tripathi", totalMes: 9, activeMes: 7, totalRetailers: 1500, retailersEngaged: 1100, unitsCovered: 4, status: "on-track" },
      { area: "Kanpur", asm: "U. Verma", totalMes: 8, activeMes: 6, totalRetailers: 1300, retailersEngaged: 920, unitsCovered: 3, status: "lagging" },
      { area: "Varanasi", asm: "S. Mishra", totalMes: 5, activeMes: 4, totalRetailers: 900, retailersEngaged: 560, unitsCovered: 2, status: "lagging" }
    ]
  },
  {
    state: "Madhya Pradesh",
    stateHead: "P. Tiwari",
    totalMes: 32,
    activeMes: 24,
    totalRetailers: 4600,
    retailersEngaged: 3050,
    unitsCovered: 3,
    status: "lagging",
    segments: { new: 736, loyal: 1564, inactive: 1380, declining: 920 },
    areas: [
      { area: "Indore", asm: "K. Agrawal", totalMes: 10, activeMes: 8, totalRetailers: 1500, retailersEngaged: 1080, unitsCovered: 4, status: "on-track" },
      { area: "Bhopal", asm: "G. Saxena", totalMes: 7, activeMes: 5, totalRetailers: 1100, retailersEngaged: 720, unitsCovered: 3, status: "lagging" }
    ]
  },
  {
    state: "West Bengal",
    stateHead: "S. Banerjee",
    totalMes: 30,
    activeMes: 22,
    totalRetailers: 4400,
    retailersEngaged: 2850,
    unitsCovered: 2,
    status: "lagging",
    segments: { new: 704, loyal: 1408, inactive: 1408, declining: 880 },
    areas: [
      { area: "Kolkata", asm: "D. Ghosh", totalMes: 12, activeMes: 9, totalRetailers: 1900, retailersEngaged: 1320, unitsCovered: 3, status: "lagging" },
      { area: "Howrah", asm: "B. Dutta", totalMes: 6, activeMes: 4, totalRetailers: 1e3, retailersEngaged: 580, unitsCovered: 2, status: "lagging" }
    ]
  },
  {
    state: "Telangana",
    stateHead: "V. Reddy",
    totalMes: 28,
    activeMes: 22,
    totalRetailers: 4200,
    retailersEngaged: 3050,
    unitsCovered: 4,
    status: "on-track",
    segments: { new: 672, loyal: 1512, inactive: 1176, declining: 840 },
    areas: [
      { area: "Hyderabad", asm: "P. Reddy", totalMes: 14, activeMes: 11, totalRetailers: 2100, retailersEngaged: 1620, unitsCovered: 5, status: "on-track" },
      { area: "Warangal", asm: "K. Rao", totalMes: 6, activeMes: 5, totalRetailers: 900, retailersEngaged: 640, unitsCovered: 3, status: "lagging" }
    ]
  },
  {
    state: "Punjab",
    stateHead: "H. Singh",
    totalMes: 22,
    activeMes: 14,
    totalRetailers: 3200,
    retailersEngaged: 1900,
    unitsCovered: 2,
    status: "lagging",
    segments: { new: 512, loyal: 960, inactive: 1024, declining: 704 },
    areas: [
      { area: "Ludhiana", asm: "G. Sandhu", totalMes: 9, activeMes: 6, totalRetailers: 1400, retailersEngaged: 880, unitsCovered: 3, status: "lagging" },
      { area: "Amritsar", asm: "T. Bedi", totalMes: 6, activeMes: 4, totalRetailers: 900, retailersEngaged: 540, unitsCovered: 2, status: "lagging" }
    ]
  },
  {
    state: "Bihar",
    stateHead: "M. Yadav",
    totalMes: 24,
    activeMes: 14,
    totalRetailers: 2900,
    retailersEngaged: 1650,
    unitsCovered: 2,
    status: "lagging",
    segments: { new: 464, loyal: 870, inactive: 928, declining: 638 },
    areas: [
      { area: "Patna", asm: "R. Kumar", totalMes: 10, activeMes: 6, totalRetailers: 1300, retailersEngaged: 760, unitsCovered: 3, status: "lagging" },
      { area: "Gaya", asm: "N. Prasad", totalMes: 5, activeMes: 3, totalRetailers: 700, retailersEngaged: 360, unitsCovered: 1, status: "yet-to-start" }
    ]
  },
  {
    state: "Odisha",
    stateHead: "B. Patra",
    totalMes: 16,
    activeMes: 9,
    totalRetailers: 2300,
    retailersEngaged: 1140,
    unitsCovered: 1,
    status: "yet-to-start",
    segments: { new: 368, loyal: 575, inactive: 805, declining: 552 },
    areas: [
      { area: "Bhubaneswar", asm: "A. Mohanty", totalMes: 8, activeMes: 5, totalRetailers: 1200, retailersEngaged: 640, unitsCovered: 2, status: "lagging" },
      { area: "Cuttack", asm: "K. Sahoo", totalMes: 4, activeMes: 2, totalRetailers: 600, retailersEngaged: 240, unitsCovered: 1, status: "yet-to-start" }
    ]
  }
];
var momTrend = [
  { month: "Nov", engagements: 42500, activeMes: 268 },
  { month: "Dec", engagements: 46800, activeMes: 281 },
  { month: "Jan", engagements: 51200, activeMes: 296 },
  { month: "Feb", engagements: 55400, activeMes: 308 },
  { month: "Mar", engagements: 59900, activeMes: 320 },
  { month: "Apr", engagements: 63700, activeMes: 332 }
];
var objectionTypes = [
  "Demand-related",
  "Working capital",
  "SKU space",
  "Competition from other brands",
  "Poor Product Quality"
];
var stateObjectionMatrix = {
  Maharashtra: { "Demand-related": 280, "Working capital": 220, "SKU space": 180, "Competition from other brands": 170, "Poor Product Quality": 110 },
  Gujarat: { "Demand-related": 220, "Working capital": 180, "SKU space": 150, "Competition from other brands": 200, "Poor Product Quality": 90 },
  Rajasthan: { "Demand-related": 240, "Working capital": 160, "SKU space": 140, "Competition from other brands": 120, "Poor Product Quality": 80 },
  Karnataka: { "Demand-related": 200, "Working capital": 170, "SKU space": 130, "Competition from other brands": 180, "Poor Product Quality": 90 },
  "Tamil Nadu": { "Demand-related": 260, "Working capital": 190, "SKU space": 150, "Competition from other brands": 160, "Poor Product Quality": 120 },
  "Uttar Pradesh": { "Demand-related": 320, "Working capital": 260, "SKU space": 200, "Competition from other brands": 140, "Poor Product Quality": 130 },
  "Madhya Pradesh": { "Demand-related": 210, "Working capital": 170, "SKU space": 130, "Competition from other brands": 110, "Poor Product Quality": 90 },
  "West Bengal": { "Demand-related": 290, "Working capital": 240, "SKU space": 170, "Competition from other brands": 130, "Poor Product Quality": 140 },
  Telangana: { "Demand-related": 180, "Working capital": 150, "SKU space": 110, "Competition from other brands": 160, "Poor Product Quality": 70 },
  Punjab: { "Demand-related": 220, "Working capital": 180, "SKU space": 140, "Competition from other brands": 120, "Poor Product Quality": 90 },
  Bihar: { "Demand-related": 260, "Working capital": 230, "SKU space": 160, "Competition from other brands": 90, "Poor Product Quality": 110 },
  Odisha: { "Demand-related": 170, "Working capital": 140, "SKU space": 100, "Competition from other brands": 80, "Poor Product Quality": 70 }
};
var areaObjections = [
  { area: "Pune", state: "Maharashtra", asm: "Rajesh Kumar", activeMes: 6, retailersAffected: { "Demand-related": 92, "Working capital": 74, "SKU space": 60, "Competition from other brands": 58, "Poor Product Quality": 36 } },
  { area: "Mumbai", state: "Maharashtra", asm: "S. Bhide", activeMes: 8, retailersAffected: { "Demand-related": 110, "Working capital": 88, "SKU space": 70, "Competition from other brands": 64, "Poor Product Quality": 44 } },
  { area: "Ahmedabad", state: "Gujarat", asm: "V. Shah", activeMes: 7, retailersAffected: { "Demand-related": 86, "Working capital": 70, "SKU space": 58, "Competition from other brands": 78, "Poor Product Quality": 32 } },
  { area: "Jaipur", state: "Rajasthan", asm: "D. Sharma", activeMes: 8, retailersAffected: { "Demand-related": 96, "Working capital": 64, "SKU space": 56, "Competition from other brands": 48, "Poor Product Quality": 32 } },
  { area: "Bengaluru", state: "Karnataka", asm: "S. Nayak", activeMes: 10, retailersAffected: { "Demand-related": 78, "Working capital": 66, "SKU space": 50, "Competition from other brands": 70, "Poor Product Quality": 35 } },
  { area: "Chennai", state: "Tamil Nadu", asm: "M. Arumugam", activeMes: 9, retailersAffected: { "Demand-related": 104, "Working capital": 76, "SKU space": 60, "Competition from other brands": 64, "Poor Product Quality": 48 } },
  { area: "Lucknow", state: "Uttar Pradesh", asm: "A. Tripathi", activeMes: 7, retailersAffected: { "Demand-related": 128, "Working capital": 104, "SKU space": 80, "Competition from other brands": 56, "Poor Product Quality": 52 } },
  { area: "Kolkata", state: "West Bengal", asm: "D. Ghosh", activeMes: 9, retailersAffected: { "Demand-related": 116, "Working capital": 96, "SKU space": 68, "Competition from other brands": 52, "Poor Product Quality": 56 } },
  { area: "Hyderabad", state: "Telangana", asm: "P. Reddy", activeMes: 11, retailersAffected: { "Demand-related": 72, "Working capital": 60, "SKU space": 44, "Competition from other brands": 64, "Poor Product Quality": 28 } },
  { area: "Patna", state: "Bihar", asm: "R. Kumar", activeMes: 6, retailersAffected: { "Demand-related": 116, "Working capital": 102, "SKU space": 70, "Competition from other brands": 40, "Poor Product Quality": 48 } }
];
var nationalInsights = [
  {
    id: "n1",
    category: "Competition",
    title: "Birla piloting EMI payments for retailers",
    summary: "Birla offering 30/60/90 day EMI on bulk orders. Particularly attractive to declining retailers with working-capital pressure. Adoption rising in west and south.",
    states: ["Maharashtra", "Gujarat", "Karnataka"],
    frequency: "Reported 22 times in last 30d",
    actionability: "High"
  },
  {
    id: "n2",
    category: "Competition",
    title: "Asian Paints bundling Putty SKUs",
    summary: "Schemes on Paints conditional on bundled Putty purchases above 50 bags. Changing monthly putty order decisions across 4 states.",
    states: ["Maharashtra", "Tamil Nadu", "Telangana", "Karnataka"],
    frequency: "Reported 31 times in last 30d",
    actionability: "High"
  },
  {
    id: "n3",
    category: "Competition",
    title: "Chetak Paints aggressive new-entrant push",
    summary: "Local sales reps from Chetak visiting top contractor-focused dealers. Multiple retailers approached in the last 2 weeks.",
    states: ["Maharashtra", "Madhya Pradesh"],
    frequency: "Reported 9 times in last 30d",
    actionability: "Medium"
  },
  {
    id: "n4",
    category: "Product Quality",
    title: "Packaging damage on monsoon dispatches",
    summary: "Retailers across north and east reporting torn outer bags on early-monsoon shipments. No product loss but visible damage hurts shelf presentation.",
    states: ["Uttar Pradesh", "West Bengal", "Bihar", "Maharashtra"],
    frequency: "Reported 26 times in last 30d",
    actionability: "High"
  },
  {
    id: "n5",
    category: "Product Quality",
    title: "Weight variance flagged on 50kg cement",
    summary: "Contractors weighing bags and reporting 0.5\u20131kg variance. QC tightening request before issue spreads.",
    states: ["Karnataka", "Tamil Nadu"],
    frequency: "Reported 7 times in last 30d",
    actionability: "Medium"
  },
  {
    id: "n6",
    category: "Schemes",
    title: "Asks for simpler retailer loyalty programme",
    summary: "Retailers prefer simple schemes with fewer tiers. JK's 4-tier slab + bonus SKU is hard to explain to contractors.",
    states: ["Maharashtra", "Gujarat", "Rajasthan", "Uttar Pradesh"],
    frequency: "Reported 18 times in last 30d",
    actionability: "High"
  },
  {
    id: "n7",
    category: "Schemes",
    title: "Quarterly points-based redemption ask",
    summary: "Loyal retailers want a points-based scheme with quarterly redemption. Current scheme is volume-locked.",
    states: ["Maharashtra", "Tamil Nadu"],
    frequency: "Reported 11 times in last 30d",
    actionability: "Medium"
  },
  {
    id: "n8",
    category: "Customer",
    title: "Contractor preference shifting to faster-setting cement",
    summary: "Younger contractors in commercial projects asking for faster-setting variants. Older base still prefers standard PPC.",
    states: ["Maharashtra", "Karnataka", "Telangana"],
    frequency: "Reported 14 times in last 30d",
    actionability: "Medium"
  },
  {
    id: "n9",
    category: "Customer",
    title: "Smaller, more frequent orders becoming the norm",
    summary: "Contractors placing 2\u20133 smaller orders per month instead of one large order, driven by cash-flow caution. Affects minimum-order incentives.",
    states: ["Maharashtra", "Gujarat", "West Bengal"],
    frequency: "Reported 16 times in last 30d",
    actionability: "Medium"
  },
  {
    id: "n10",
    category: "Demand",
    title: "Demand dip after early monsoon onset",
    summary: "Early monsoon onset has paused 30+ small construction sites in north and central. Retailers expect ~20% softer demand for the next 3 weeks.",
    states: ["Uttar Pradesh", "Madhya Pradesh", "Maharashtra"],
    frequency: "Reported 19 times in last 30d",
    actionability: "High"
  },
  {
    id: "n11",
    category: "Demand",
    title: "Festival-led spike expected in white cement",
    summary: "Retailers report contractors stocking up for festival re-finishing work. White cement and putty enquiries up week-on-week.",
    states: ["Gujarat", "Rajasthan", "Maharashtra"],
    frequency: "Reported 12 times in last 30d",
    actionability: "Medium"
  },
  {
    id: "n12",
    category: "Demand",
    title: "Infra-led structural demand uptick",
    summary: "Highway and metro projects driving sustained PPC demand in select states. Opportunity to allocate more SKU coverage.",
    states: ["Telangana", "Karnataka", "Tamil Nadu"],
    frequency: "Reported 8 times in last 30d",
    actionability: "Medium"
  }
];
var topMEs = [
  { id: "lme1", name: "Vikas Patil", state: "Maharashtra", area: "Pune SW", monthlyEngagements: [180, 188, 192, 196, 198, 204] },
  { id: "lme2", name: "Sunil Sharma", state: "Maharashtra", area: "Pune NE", monthlyEngagements: [162, 170, 174, 180, 184, 190] },
  { id: "lme3", name: "G. Sandhu", state: "Punjab", area: "Ludhiana", monthlyEngagements: [150, 158, 162, 168, 176, 182] },
  { id: "lme4", name: "M. Arumugam", state: "Tamil Nadu", area: "Chennai", monthlyEngagements: [148, 152, 160, 168, 172, 178] },
  { id: "lme5", name: "S. Nayak", state: "Karnataka", area: "Bengaluru", monthlyEngagements: [140, 148, 156, 162, 170, 176] },
  { id: "lme6", name: "V. Shah", state: "Gujarat", area: "Ahmedabad", monthlyEngagements: [138, 146, 152, 158, 166, 172] },
  { id: "lme7", name: "P. Reddy", state: "Telangana", area: "Hyderabad", monthlyEngagements: [136, 144, 150, 156, 164, 170] },
  { id: "lme8", name: "D. Sharma", state: "Rajasthan", area: "Jaipur", monthlyEngagements: [132, 140, 146, 152, 160, 168] }
];

// src/lib/mcp/tools/list-market-insights.ts
var list_market_insights_default = defineTool3({
  name: "list_market_insights",
  title: "List market insights",
  description: "List field-reported market insights (competition, product quality, schemes, customer, demand) with frequency and actionability.",
  inputSchema: {
    category: z3.enum(["Competition", "Product Quality", "Schemes", "Customer", "Demand"]).optional().describe("Filter by insight category."),
    state: z3.string().optional().describe("Filter to insights reported in a given state.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, state }) => {
    const rows = nationalInsights.filter(
      (i) => (!category || i.category === category) && (!state || i.states.some((s) => s.toLowerCase() === state.toLowerCase()))
    );
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, insights: rows }
    };
  }
});

// src/lib/mcp/tools/list-objections.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_objections_default = defineTool4({
  name: "list_objections",
  title: "List retailer objections",
  description: "Retailer objection mix \u2014 overall share, per-state counts and per-area breakdown. Optionally scope to one state.",
  inputSchema: {
    state: z4.string().optional().describe("Restrict counts to a single state, e.g. 'Maharashtra'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ state }) => {
    const key = state ? Object.keys(stateObjectionMatrix).find((s) => s.toLowerCase() === state.toLowerCase()) : void 0;
    const payload = {
      objectionTypes: [...objectionTypes],
      overallSharePercent: objectionBreakdown,
      stateCounts: key ? { [key]: stateObjectionMatrix[key] } : stateObjectionMatrix,
      areaBreakdown: areaObjections
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-engagement-playbook.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var get_engagement_playbook_default = defineTool5({
  name: "get_engagement_playbook",
  title: "Get engagement playbook",
  description: "Field engagement playbook: conversation themes, discussion points, common retailer objections and the recommended responses / best practices.",
  inputSchema: {
    theme: z5.string().optional().describe("Filter themes by id or part of the title.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ theme }) => {
    const q = theme?.trim().toLowerCase();
    const themes = q ? engagementThemes.filter((t) => t.id === q || t.title.toLowerCase().includes(q)) : engagementThemes;
    const payload = { themes, discussionPoints };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-engagement-overview.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var get_engagement_overview_default = defineTool6({
  name: "get_engagement_overview",
  title: "Get engagement overview",
  description: "National retailer-engagement overview: headline KPIs, month-on-month trend, per-state coverage and the top-performing marketing executives.",
  inputSchema: {
    state: z6.string().optional().describe("Restrict the state breakdown to one state.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ state }) => {
    const stateRows = state ? states.filter((s) => s.state.toLowerCase() === state.toLowerCase()) : states;
    const payload = {
      kpis: {
        totalRetailers: NATIONAL_TOTAL_RETAILERS,
        retailersEngaged: NATIONAL_RETAILERS_ENGAGED,
        totalMes: NATIONAL_TOTAL_MES,
        activeMes: NATIONAL_ACTIVE_MES,
        totalAsms: NATIONAL_TOTAL_ASMS,
        avgEngagementsPerRetailer: NATIONAL_AVG_ENGAGEMENT_PER_RETAILER,
        benchmarkEngagementsPerRetailer: ENGAGEMENT_BENCHMARK_PER_RETAILER
      },
      monthOnMonthTrend: momTrend,
      states: stateRows,
      topMarketingExecutives: topMEs
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "jk-retailer-engagement-system",
  title: "JK Retailer Engagement System",
  version: "0.1.0",
  instructions: "Tools for the JK Cement Retailer Engagement System. Read retailer profiles and segments, field-reported market insights, retailer objection patterns, the engagement playbook (talk tracks and objection handling), and national/state engagement performance. All data is read-only demo data.",
  tools: [
    list_retailers_default,
    get_retailer_default,
    list_market_insights_default,
    list_objections_default,
    get_engagement_playbook_default,
    get_engagement_overview_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
